apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: test-installation
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3050
