apiVersion: v1
kind: Service
metadata:
  name: gui-service
  namespace: test-installation
spec:
  type: LoadBalancer
  loadBalancerIP: 35.241.214.139
  selector:
    app: gui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
